language: objective-c
osx_image: xcode7

script:
    - set -o pipefail
    - xcodebuild -project SwiftCheck.xcodeproj -scheme SwiftCheck -sdk macosx ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c
    - xcodebuild -project SwiftCheck.xcodeproj -scheme SwiftCheck-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build test | xcpretty -c
