env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - git submodule update --init --recursive
        - curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
      script:
        - . ~/.swiftenv/init
        - swift build
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - pod lib lint
  - set -o pipefail
  - carthage build --no-skip-current
  - xcodebuild test -scheme SwiftCheck-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p'
  - script/cibuild SwiftCheck SwiftCheck-iOS
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d781e1bcbabade5de35
    on_success: always
    on_failure: always
    on_start: always
